<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Medication;

class MedicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $medications = [
            // Analgésicos y Antiinflamatorios
            [
                'commercial_name' => 'Tylenol 500mg',
                'generic_name' => 'Acetaminofén',
                'manufacturer' => 'Johnson & Johnson',
                'barcode' => '7501234567890',
                'category' => 'Analgésicos',
                'presentation' => 'Tableta',
                'concentration' => '500mg',
                'administration_route' => 'Oral',
                'requires_prescription' => false,
                'controlled' => false,
                'current_stock' => 500,
                'min_stock' => 50,
                'max_stock' => 1000,
                'location' => 'Estante A1',
                'expiration_date' => '2025-12-31',
                'lot_number' => 'PAR2024001',
                'unit_cost' => 0.15,
                'sale_price' => 0.25,
                'status' => 'active',
                'indications' => 'Analgésico y antipirético para dolor leve a moderado',
                'contraindications' => 'Hipersensibilidad al acetaminofén, insuficiencia hepática severa',
                'side_effects' => 'Raras: náuseas, erupciones cutáneas',
                'drug_interactions' => 'Alcohol, warfarina',
                'storage_notes' => 'Conservar en lugar seco a temperatura ambiente'
            ],
            [
                'commercial_name' => 'Advil 400mg',
                'generic_name' => 'Ibuprofeno',
                'manufacturer' => 'Pfizer',
                'barcode' => '7501234567891',
                'category' => 'AINES',
                'presentation' => 'Tableta',
                'concentration' => '400mg',
                'administration_route' => 'Oral',
                'requires_prescription' => false,
                'controlled' => false,
                'current_stock' => 300,
                'min_stock' => 40,
                'max_stock' => 600,
                'location' => 'Estante A2',
                'expiration_date' => '2025-08-15',
                'lot_number' => 'IBU2024002',
                'unit_cost' => 0.20,
                'sale_price' => 0.35,
                'status' => 'active',
                'indications' => 'Antiinflamatorio no esteroideo para dolor e inflamación',
                'contraindications' => 'Úlcera péptica activa, insuficiencia renal severa',
                'side_effects' => 'Molestias gastrointestinales, mareos',
                'drug_interactions' => 'Anticoagulantes, ACE inhibidores',
                'storage_notes' => 'Conservar en lugar seco, protegido de la luz'
            ],
            [
                'commercial_name' => 'Voltaren 50mg',
                'generic_name' => 'Diclofenaco Sódico',
                'manufacturer' => 'Novartis',
                'barcode' => '7501234567892',
                'category' => 'AINES',
                'presentation' => 'Tableta',
                'concentration' => '50mg',
                'administration_route' => 'Oral',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 200,
                'min_stock' => 30,
                'max_stock' => 400,
                'location' => 'Estante A3',
                'expiration_date' => '2025-10-20',
                'lot_number' => 'DIC2024003',
                'unit_cost' => 0.25,
                'sale_price' => 0.45,
                'status' => 'active',
                'indications' => 'Antiinflamatorio para dolor articular y muscular',
                'contraindications' => 'Hipersensibilidad a AINEs, úlcera péptica',
                'side_effects' => 'Náuseas, dolor abdominal, mareos',
                'drug_interactions' => 'Warfarina, digoxina, metotrexato',
                'storage_notes' => 'Conservar a temperatura ambiente, protegido de la humedad'
            ],
            
            // Antibióticos
            [
                'commercial_name' => 'Amoxil 500mg',
                'generic_name' => 'Amoxicilina',
                'manufacturer' => 'GlaxoSmithKline',
                'barcode' => '7501234567893',
                'category' => 'Antibióticos',
                'presentation' => 'Cápsula',
                'concentration' => '500mg',
                'administration_route' => 'Oral',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 150,
                'min_stock' => 25,
                'max_stock' => 300,
                'location' => 'Estante B1',
                'expiration_date' => '2025-06-30',
                'lot_number' => 'AMX2024004',
                'unit_cost' => 0.50,
                'sale_price' => 0.80,
                'status' => 'active',
                'indications' => 'Antibiótico betalactámico de amplio espectro',
                'contraindications' => 'Alergia a penicilinas',
                'side_effects' => 'Diarrea, náuseas, erupciones cutáneas',
                'drug_interactions' => 'Metotrexato, anticoagulantes orales',
                'storage_notes' => 'Conservar en lugar fresco y seco'
            ],
            [
                'commercial_name' => 'Zithromax 250mg',
                'generic_name' => 'Azitromicina',
                'manufacturer' => 'Pfizer',
                'barcode' => '7501234567894',
                'category' => 'Antibióticos',
                'presentation' => 'Tableta',
                'concentration' => '250mg',
                'administration_route' => 'Oral',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 80,
                'min_stock' => 15,
                'max_stock' => 160,
                'location' => 'Estante B2',
                'expiration_date' => '2025-09-15',
                'lot_number' => 'AZI2024005',
                'unit_cost' => 0.80,
                'sale_price' => 1.20,
                'status' => 'active',
                'indications' => 'Antibiótico macrólido para infecciones respiratorias',
                'contraindications' => 'Hipersensibilidad a macrólidos',
                'side_effects' => 'Náuseas, diarrea, dolor abdominal',
                'drug_interactions' => 'Digoxina, warfarina, ergotamina',
                'storage_notes' => 'Conservar a temperatura ambiente'
            ],
            [
                'commercial_name' => 'Keflex 500mg',
                'generic_name' => 'Cefalexina',
                'manufacturer' => 'Eli Lilly',
                'barcode' => '7501234567895',
                'category' => 'Antibióticos',
                'presentation' => 'Cápsula',
                'concentration' => '500mg',
                'administration_route' => 'Oral',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 120,
                'min_stock' => 20,
                'max_stock' => 240,
                'location' => 'Estante B3',
                'expiration_date' => '2025-11-10',
                'lot_number' => 'CEF2024006',
                'unit_cost' => 0.60,
                'sale_price' => 0.95,
                'status' => 'active',
                'indications' => 'Antibiótico cefalosporina de primera generación',
                'contraindications' => 'Alergia a cefalosporinas',
                'side_effects' => 'Diarrea, náuseas, vómitos',
                'drug_interactions' => 'Probenecid, aminoglucósidos',
                'storage_notes' => 'Conservar en lugar seco, protegido de la luz'
            ],
            
            // Cardiovasculares
            [
                'commercial_name' => 'Cozaar 50mg',
                'generic_name' => 'Losartán Potásico',
                'manufacturer' => 'Merck',
                'barcode' => '7501234567896',
                'category' => 'Antihipertensivos',
                'presentation' => 'Tableta',
                'concentration' => '50mg',
                'administration_route' => 'Oral',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 250,
                'min_stock' => 35,
                'max_stock' => 500,
                'location' => 'Estante C1',
                'expiration_date' => '2026-01-15',
                'lot_number' => 'LOS2024007',
                'unit_cost' => 0.40,
                'sale_price' => 0.65,
                'status' => 'active',
                'indications' => 'Antagonista de receptores de angiotensina II',
                'contraindications' => 'Embarazo, hiperpotasemia severa',
                'side_effects' => 'Mareos, fatiga, hiperpotasemia',
                'drug_interactions' => 'Diuréticos ahorradores de potasio, litio',
                'storage_notes' => 'Conservar a temperatura ambiente, protegido de la humedad'
            ],
            [
                'commercial_name' => 'Vasotec 10mg',
                'generic_name' => 'Enalapril Maleato',
                'manufacturer' => 'MSD',
                'barcode' => '7501234567897',
                'category' => 'Antihipertensivos',
                'presentation' => 'Tableta',
                'concentration' => '10mg',
                'administration_route' => 'Oral',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 180,
                'min_stock' => 30,
                'max_stock' => 360,
                'location' => 'Estante C2',
                'expiration_date' => '2025-07-20',
                'lot_number' => 'ENA2024008',
                'unit_cost' => 0.35,
                'sale_price' => 0.55,
                'status' => 'active',
                'indications' => 'Inhibidor de la enzima convertidora de angiotensina',
                'contraindications' => 'Embarazo, angioedema previo',
                'side_effects' => 'Tos seca, hipotensión, hiperpotasemia',
                'drug_interactions' => 'Diuréticos, litio, AINEs',
                'storage_notes' => 'Conservar en lugar seco a temperatura ambiente'
            ],
            [
                'commercial_name' => 'Lipitor 20mg',
                'generic_name' => 'Atorvastatina Cálcica',
                'manufacturer' => 'Pfizer',
                'barcode' => '7501234567898',
                'category' => 'Hipolipemiantes',
                'presentation' => 'Tableta',
                'concentration' => '20mg',
                'administration_route' => 'Oral',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 160,
                'min_stock' => 25,
                'max_stock' => 320,
                'location' => 'Estante C3',
                'expiration_date' => '2025-12-05',
                'lot_number' => 'ATO2024009',
                'unit_cost' => 0.75,
                'sale_price' => 1.15,
                'status' => 'active',
                'indications' => 'Estatina para reducir colesterol y triglicéridos',
                'contraindications' => 'Enfermedad hepática activa, embarazo',
                'side_effects' => 'Mialgia, cefalea, trastornos gastrointestinales',
                'drug_interactions' => 'Ciclosporina, digoxina, warfarina',
                'storage_notes' => 'Conservar a temperatura ambiente, protegido de la luz'
            ],
            
            // Antidiabéticos
            [
                'commercial_name' => 'Glucophage 850mg',
                'generic_name' => 'Metformina Clorhidrato',
                'manufacturer' => 'Bristol-Myers Squibb',
                'barcode' => '7501234567899',
                'category' => 'Antidiabéticos',
                'presentation' => 'Tableta',
                'concentration' => '850mg',
                'administration_route' => 'Oral',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 220,
                'min_stock' => 40,
                'max_stock' => 440,
                'location' => 'Estante D1',
                'expiration_date' => '2026-03-10',
                'lot_number' => 'MET2024010',
                'unit_cost' => 0.25,
                'sale_price' => 0.40,
                'status' => 'active',
                'indications' => 'Hipoglucemiante oral para diabetes tipo 2',
                'contraindications' => 'Insuficiencia renal, acidosis metabólica',
                'side_effects' => 'Náuseas, diarrea, sabor metálico',
                'drug_interactions' => 'Alcohol, contrastes yodados',
                'storage_notes' => 'Conservar en lugar seco a temperatura ambiente'
            ],
            [
                'commercial_name' => 'Daonil 5mg',
                'generic_name' => 'Glibenclamida',
                'manufacturer' => 'Sanofi',
                'barcode' => '7501234567900',
                'category' => 'Antidiabéticos',
                'presentation' => 'Tableta',
                'concentration' => '5mg',
                'administration_route' => 'Oral',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 140,
                'min_stock' => 20,
                'max_stock' => 280,
                'location' => 'Estante D2',
                'expiration_date' => '2025-09-25',
                'lot_number' => 'GLI2024011',
                'unit_cost' => 0.20,
                'sale_price' => 0.35,
                'status' => 'active',
                'indications' => 'Sulfonilurea para diabetes tipo 2',
                'contraindications' => 'Diabetes tipo 1, cetoacidosis diabética',
                'side_effects' => 'Hipoglucemia, aumento de peso',
                'drug_interactions' => 'Alcohol, beta-bloqueadores, warfarina',
                'storage_notes' => 'Conservar en lugar seco, protegido de la luz'
            ],
            
            // Respiratorios
            [
                'commercial_name' => 'Ventolin HFA',
                'generic_name' => 'Salbutamol Sulfato',
                'manufacturer' => 'GlaxoSmithKline',
                'barcode' => '7501234567901',
                'category' => 'Broncodilatadores',
                'presentation' => 'Inhalador',
                'concentration' => '100mcg/dosis',
                'administration_route' => 'Inhalatoria',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 50,
                'min_stock' => 10,
                'max_stock' => 100,
                'location' => 'Refrigerador A',
                'expiration_date' => '2025-08-30',
                'lot_number' => 'SAL2024012',
                'unit_cost' => 5.50,
                'sale_price' => 8.50,
                'status' => 'active',
                'indications' => 'Broncodilatador de acción rápida para asma',
                'contraindications' => 'Hipersensibilidad al salbutamol',
                'side_effects' => 'Temblor, taquicardia, nerviosismo',
                'drug_interactions' => 'Beta-bloqueadores, diuréticos',
                'storage_notes' => 'No refrigerar, conservar a temperatura ambiente'
            ],
            [
                'commercial_name' => 'Claritin 10mg',
                'generic_name' => 'Loratadina',
                'manufacturer' => 'Schering-Plough',
                'barcode' => '7501234567902',
                'category' => 'Antihistamínicos',
                'presentation' => 'Tableta',
                'concentration' => '10mg',
                'administration_route' => 'Oral',
                'requires_prescription' => false,
                'controlled' => false,
                'current_stock' => 180,
                'min_stock' => 25,
                'max_stock' => 360,
                'location' => 'Estante E1',
                'expiration_date' => '2025-11-15',
                'lot_number' => 'LOR2024013',
                'unit_cost' => 0.55,
                'sale_price' => 0.85,
                'status' => 'active',
                'indications' => 'Antihistamínico para alergias',
                'contraindications' => 'Hipersensibilidad a loratadina',
                'side_effects' => 'Somnolencia leve, cefalea',
                'drug_interactions' => 'Alcohol, depresores del SNC',
                'storage_notes' => 'Conservar en lugar seco a temperatura ambiente'
            ],
            
            // Gastrointestinales
            [
                'commercial_name' => 'Prilosec 20mg',
                'generic_name' => 'Omeprazol',
                'manufacturer' => 'AstraZeneca',
                'barcode' => '7501234567903',
                'category' => 'Antiulcerosos',
                'presentation' => 'Cápsula',
                'concentration' => '20mg',
                'administration_route' => 'Oral',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 200,
                'min_stock' => 30,
                'max_stock' => 400,
                'location' => 'Estante F1',
                'expiration_date' => '2025-12-20',
                'lot_number' => 'OME2024014',
                'unit_cost' => 0.45,
                'sale_price' => 0.75,
                'status' => 'active',
                'indications' => 'Inhibidor de la bomba de protones',
                'contraindications' => 'Hipersensibilidad al omeprazol',
                'side_effects' => 'Cefalea, náuseas, diarrea',
                'drug_interactions' => 'Warfarina, digoxina, ketoconazol',
                'storage_notes' => 'Conservar en lugar seco, protegido de la humedad'
            ],
            [
                'commercial_name' => 'Motilium 10mg',
                'generic_name' => 'Domperidona',
                'manufacturer' => 'Janssen',
                'barcode' => '7501234567904',
                'category' => 'Procinéticos',
                'presentation' => 'Tableta',
                'concentration' => '10mg',
                'administration_route' => 'Oral',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 120,
                'min_stock' => 20,
                'max_stock' => 240,
                'location' => 'Estante F2',
                'expiration_date' => '2025-10-08',
                'lot_number' => 'DOM2024015',
                'unit_cost' => 0.60,
                'sale_price' => 0.95,
                'status' => 'active',
                'indications' => 'Procinético para náuseas y vómitos',
                'contraindications' => 'Obstrucción intestinal, prolactinoma',
                'side_effects' => 'Sequedad de boca, cefalea',
                'drug_interactions' => 'Ketoconazol, eritromicina',
                'storage_notes' => 'Conservar a temperatura ambiente'
            ],
            
            // Vitaminas y Suplementos
            [
                'commercial_name' => 'Vitamin D3 1000UI',
                'generic_name' => 'Colecalciferol',
                'manufacturer' => 'Nature Made',
                'barcode' => '7501234567905',
                'category' => 'Vitaminas',
                'presentation' => 'Cápsula blanda',
                'concentration' => '1000UI',
                'administration_route' => 'Oral',
                'requires_prescription' => false,
                'controlled' => false,
                'current_stock' => 300,
                'min_stock' => 50,
                'max_stock' => 600,
                'location' => 'Estante G1',
                'expiration_date' => '2026-02-28',
                'lot_number' => 'VIT2024016',
                'unit_cost' => 0.18,
                'sale_price' => 0.30,
                'status' => 'active',
                'indications' => 'Suplemento de vitamina D para salud ósea',
                'contraindications' => 'Hipercalcemia, hipervitaminosis D',
                'side_effects' => 'Raras: náuseas, vómitos con sobredosis',
                'drug_interactions' => 'Digoxina, diuréticos tiazídicos',
                'storage_notes' => 'Conservar en lugar fresco y seco'
            ],
            [
                'commercial_name' => 'B-Complex 50mg',
                'generic_name' => 'Complejo Vitamínico B',
                'manufacturer' => 'Centrum',
                'barcode' => '7501234567906',
                'category' => 'Vitaminas',
                'presentation' => 'Tableta',
                'concentration' => '50mg',
                'administration_route' => 'Oral',
                'requires_prescription' => false,
                'controlled' => false,
                'current_stock' => 250,
                'min_stock' => 40,
                'max_stock' => 500,
                'location' => 'Estante G2',
                'expiration_date' => '2026-01-10',
                'lot_number' => 'COM2024017',
                'unit_cost' => 0.28,
                'sale_price' => 0.45,
                'status' => 'active',
                'indications' => 'Complejo vitamínico del grupo B',
                'contraindications' => 'Hipersensibilidad a algún componente',
                'side_effects' => 'Raras: náuseas, coloración amarilla de orina',
                'drug_interactions' => 'Levodopa, fenitoína',
                'storage_notes' => 'Conservar en lugar seco, protegido de la luz'
            ],
            
            // Hormonales
            [
                'commercial_name' => 'Synthroid 50mcg',
                'generic_name' => 'Levotiroxina Sódica',
                'manufacturer' => 'Abbott',
                'barcode' => '7501234567907',
                'category' => 'Hormonas Tiroideas',
                'presentation' => 'Tableta',
                'concentration' => '50mcg',
                'administration_route' => 'Oral',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 180,
                'min_stock' => 30,
                'max_stock' => 360,
                'location' => 'Estante H1',
                'expiration_date' => '2025-11-30',
                'lot_number' => 'LEV2024018',
                'unit_cost' => 0.50,
                'sale_price' => 0.85,
                'status' => 'active',
                'indications' => 'Hormona tiroidea sintética para hipotiroidismo',
                'contraindications' => 'Tirotoxicosis, insuficiencia suprarrenal',
                'side_effects' => 'Palpitaciones, nerviosismo, insomnio',
                'drug_interactions' => 'Warfarina, digoxina, insulina',
                'storage_notes' => 'Conservar en lugar seco, protegido de la luz y humedad'
            ],
            
            // Productos con stock bajo (para testing)
            [
                'commercial_name' => 'Tramal 50mg',
                'generic_name' => 'Tramadol Clorhidrato',
                'manufacturer' => 'Grünenthal',
                'barcode' => '7501234567908',
                'category' => 'Analgésicos Opioides',
                'presentation' => 'Cápsula',
                'concentration' => '50mg',
                'administration_route' => 'Oral',
                'requires_prescription' => true,
                'controlled' => true,
                'current_stock' => 15, // Stock bajo
                'min_stock' => 20,
                'max_stock' => 100,
                'location' => 'Caja Fuerte A',
                'expiration_date' => '2025-06-15',
                'lot_number' => 'TRA2024019',
                'unit_cost' => 0.80,
                'sale_price' => 1.25,
                'status' => 'active',
                'indications' => 'Analgésico opioide para dolor moderado a severo',
                'contraindications' => 'Depresión respiratoria, intoxicación alcohólica',
                'side_effects' => 'Náuseas, mareos, somnolencia, constipación',
                'drug_interactions' => 'ISRS, IMAO, carbamazepina',
                'storage_notes' => 'Medicamento controlado - Caja fuerte'
            ],
            [
                'commercial_name' => 'Humulin N 100UI/mL',
                'generic_name' => 'Insulina Humana NPH',
                'manufacturer' => 'Eli Lilly',
                'barcode' => '7501234567909',
                'category' => 'Insulinas',
                'presentation' => 'Vial 10mL',
                'concentration' => '100UI/mL',
                'administration_route' => 'Subcutánea',
                'requires_prescription' => true,
                'controlled' => false,
                'current_stock' => 8, // Stock bajo
                'min_stock' => 12,
                'max_stock' => 50,
                'location' => 'Refrigerador B',
                'expiration_date' => '2025-04-30', // Próximo a vencer
                'lot_number' => 'INS2024020',
                'unit_cost' => 18.00,
                'sale_price' => 25.00,
                'status' => 'active',
                'indications' => 'Insulina de acción intermedia',
                'contraindications' => 'Hipoglucemia, hipersensibilidad a insulina',
                'side_effects' => 'Hipoglucemia, reacciones en sitio de inyección',
                'drug_interactions' => 'Beta-bloqueadores, alcohol, corticosteroides',
                'storage_notes' => 'Refrigerar entre 2-8°C, no congelar'
            ]
        ];

        foreach ($medications as $medicationData) {
            // Verificar si el medicamento ya existe por código de barras
            $existingMedication = Medication::where('barcode', $medicationData['barcode'])->first();
            
            if ($existingMedication) {
                $this->command->info("⚠️  Medicamento {$medicationData['commercial_name']} ya existe, saltando...");
                continue;
            }
            
            Medication::create($medicationData);
            $this->command->info("✅ Medicamento creado: {$medicationData['commercial_name']}");
        }

        $this->command->info('✅ Proceso de creación de medicamentos completado!');
        $this->command->warn('⚠️  Algunos medicamentos tienen stock bajo y próximos a vencer para pruebas.');
    }
} 